/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus_booking;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.MongoClient;
import com.mongodb.MongoException;
import java.net.UnknownHostException;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
//import java.lang.NullPointerException;
//import java.util.*;
/**
 *
 * @author charu
 */
public class Buses extends javax.swing.JFrame {

    /**
     * Creates new form Buses
     */
    public Buses() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        bus_no1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bname1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        maxseats1 = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fare1 = new javax.swing.JTextField();
        type1 = new javax.swing.JComboBox();
        save = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        desn1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bus Booking\n");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(825, 659));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus_booking/busing.gif"))); // NOI18N
        jLabel1.setText("Bus Booking System");
        jLabel1.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Bus details");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Bus_no");

        bname1.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Bus_name");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Type");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("Max_seats");

        back.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        back.setForeground(new java.awt.Color(0, 0, 102));
        back.setText("<<Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Destination");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setText("Fare");

        fare1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fare1ActionPerformed(evt);
            }
        });

        type1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        type1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Bus Type", "AC", "Non-AC", "Sleeper" }));
        type1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                type1ItemStateChanged(evt);
            }
        });
        type1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type1ActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        save.setForeground(new java.awt.Color(0, 0, 102));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setText("Source");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setText("All buses will depart from \"PUNE\"");

        desn1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        desn1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select your Destination", "Aurangabad", "Mumbai", "Nashik", "Nagpur", "Shirdi" }));
        desn1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                desn1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(save)
                                .addGap(109, 109, 109)
                                .addComponent(back))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(bus_no1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bname1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(type1, javax.swing.GroupLayout.Alignment.LEADING, 0, 181, Short.MAX_VALUE)
                                        .addComponent(maxseats1, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(fare1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(desn1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(474, 474, 474)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bus_no1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(type1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxseats1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(desn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fare1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(back))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
this.setVisible(false);
new bchoice1().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void fare1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fare1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fare1ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

        try
    {
          MongoClient mongoClient = new MongoClient("localhost", 27017);
        DB db = mongoClient.getDB("BusBooking");
        DBCollection coll = db.getCollection("Buses");
        
         
	String bus_no,bname,fare;
       String maxseats;
     
         Object type,desn;   
        
          
        bus_no = bus_no1.getText();
        bname = bname1.getText();
        type = type1.getSelectedItem();
        maxseats=maxseats1.getText();
        desn = desn1.getSelectedItem();
        fare = fare1.getText();
       
       String Bname="[a-zA-Z]*" ;
      
      
      if(bname.equals("") || bus_no.equals("") || type.equals("") || maxseats.equals("") || fare.equals("") || desn.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Fill all Fields");
        } 
     else if(!bname.matches(Bname))///name Validation
     {
       JOptionPane.showMessageDialog(null,"Please Enter valid Name");
       bname1.setText(null);
      }
      else  if((!maxseats.matches("[0-9.]")&&(maxseats.length())!=2))//Max seat no validation
      {
          JOptionPane.showMessageDialog(null,"Please Enter seats no between 1 to 50");
          maxseats1.setText(null);
      }
      /* else if(!desn.matches(Bname))///name Validation
     {
       JOptionPane.showMessageDialog(null,"enter valid destination");
       desn1.setText(null);
      }*/
     /* else  if((!fare.matches("[0-9.]")&&(fare.length())!=3))//fare validation
      {
          JOptionPane.showMessageDialog(null,"Please Enter fare between 100 to 999");
          fare1.setText(null);
      }*/
   
      else {
     int i=Integer.parseInt(bus_no);
      int i1=Integer.parseInt(maxseats);
      
      BasicDBObject doc = new BasicDBObject("_id",i).append("Bus_name", bname).append("Type",type).append("Maxseats",i1).append("Destination",desn).append("Fare", fare);
      coll.insert(doc);
      JOptionPane.showMessageDialog(null,"Data inserted Successfully!!!");
       bus_no1.setText(null);

          bname1.setText(null);
          type1.setSelectedItem(null);
          maxseats1.setText(null);
          desn1.setSelectedItem(null);
          fare1.setText(null);
         
       }
          }
            
        catch(UnknownHostException e){}
        catch(MongoException m){JOptionPane.showMessageDialog(null,"Same id entry not allowed !!");}
         
                   // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void type1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type1ActionPerformed

    private void desn1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_desn1ItemStateChanged
        
       /* Object i=desn1.getSelectedItem();
        Object j=type1.getSelectedItem();
        if((i.equals("Aurangabad"))&& (j.equals("Sleeper") )){fare1.setText("1020");}
        else if(i.equals("Aurangabad")&& j.equals("AC") ){ fare1.setText("680");}
        else if(i.equals("Aurangabad")&& j.equals("Non-AC") ){fare1.setText("340");}
        
       else if(i.equals("Mumbai")&& j.equals("Sleeper")){fare1.setText("1350");}   
        else if(i.equals("Mumbai")&& j.equals("AC") ){fare1.setText("900");}
        else if(i.equals("Mumbai")&& j.equals("Non-AC") ){fare1.setText("450");}
         
        else if((i.equals("Nashik"))&& (j.equals("Sleeper") )){fare1.setText("960");} 
         else if(i.equals("Nashik")&& j.equals("AC") ){fare1.setText("640");}
         else if(i.equals("Nashik")&& j.equals("Non-AC") ){fare1.setText("320");}
         
         else if((i.equals("Nagpur"))&& (j.equals("Sleeper") )){fare1.setText("1500");}  
           else if(i.equals("Nagpur")&& j.equals("AC") ){fare1.setText("1200");}
           else if(i.equals("Nagpur")&& j.equals("Non-AC") ){fare1.setText("800");}
          
          else if((i.equals("Shirdi"))&& (j.equals("Sleeper") )){ fare1.setText("900"); } 
            else if(i.equals("Shirdi")&& j.equals("AC") ){fare1.setText("600");}
            else if(i.equals("Shirdi")&& j.equals("Non-AC") ){fare1.setText("300");}*/
            
    // TODO add your handling code here:
    }//GEN-LAST:event_desn1ItemStateChanged
    
    private void type1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_type1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_type1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField bname1;
    private javax.swing.JTextField bus_no1;
    private javax.swing.JComboBox desn1;
    private javax.swing.JTextField fare1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField maxseats1;
    private javax.swing.JButton save;
    private javax.swing.JComboBox type1;
    // End of variables declaration//GEN-END:variables
}
